 CREATE PROCEDURE ADDITION @FIRSTNO INT, @SECONDNO INT AS
 BEGIN
     SET @FIRSTNO=(@FIRSTNO + @SECONDNO)
     SELECT CONCAT('Total is: ', @FIRSTNO);
END;
EXEC ADDITION 10,15

CREATE PROCEDURE MULTIPLY @FIRSTNO INT, @SECONDNO INT AS
 BEGIN
     SET @FIRSTNO= (@FIRSTNO * @SECONDNO);
     SELECT CONCAT('Total is: ', @FIRSTNO);
END;
EXECUTE MULTIPLY 10, 4;

CREATE PROCEDURE TRANSFER @Sender NVARCHAR(10), @Reciever NVARCHAR(10), @Amount INT AS 
BEGIN 
UPDATE ACCOUNT 
Set Balance = (Balance-@Amount)
Where Acctno = @Sender;

UPDATE ACCOUNT
Set Balance = (Balance + @Amount)
WHERE Acctno = @Reciever;

END;

EXECUTE TRANSFER 1, 2 , 10

CREATE TABLE ACCOUNT(
AcctNo NVARCHAR(10) PRIMARY KEY,
Fname NVARCHAR(100),
Lname NVARCHAR(100),
CreditLimit NVARCHAR(10),
Balance INT,
)

CREATE TABLE Log(
    OrigAcct NVARCHAR(10),
    LogDateTime DATETIME,
    RecAcct NVARCHAR(10),
    Amount NVARCHAR(10)
    CONSTRAINT CK_LOG PRIMARY KEY (OrigAcct,LogDateTime),
    FOREIGN KEY (OrigAcct) REFERENCES ACCOUNT(AcctNo),
    FOREIGN KEY (RecAcct) REFERENCES ACCOUNT(AcctNo)
)

SELECT * FROM ACCOUNT

INSERT INTO ACCOUNT(AcctNo,Fname,Lname,CreditLimit,Balance) VALUES(1 ,'Matt','Coates', 10, 100)
INSERT INTO ACCOUNT(AcctNo,Fname,Lname,CreditLimit,Balance) VALUES(2 ,'Coates','Matt', 10, 100)
CREATE DATABASE TEST10351210
USE TEST10351210
DROP PROCEDURE ADDITION
DROP PROCEDURE MULTIPLY
DROP PROCEDURE TRANSFER
DROP TABLE LOG
DROP TABLE ACCOUNT
DROP DATABASE TEST10351210